# Generated by Django 5.2.7 on 2025-10-15 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('mobile_number', models.CharField(max_length=15)),
                ('place', models.CharField(max_length=200)),
                ('interested_course', models.CharField(max_length=200)),
                ('course_mode', models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline')], default='Offline', max_length=10)),
                ('select_center', models.CharField(max_length=200)),
                ('additional_message', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
