# Generated by Django 5.2.7 on 2025-10-23 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.SlugField(primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('short_description', models.TextField()),
                ('category', models.CharField(max_length=255)),
                ('duration', models.CharField(max_length=100)),
                ('level', models.CharField(max_length=100)),
                ('mode', models.CharField(max_length=100)),
                ('certification', models.CharField(max_length=255)),
                ('image', models.URLField(blank=True, max_length=500, null=True)),
                ('overview', models.TextField()),
                ('modules', models.JSONField(blank=True, default=list)),
                ('career_opportunities', models.JSONField(blank=True, default=list)),
                ('tools', models.JSONField(blank=True, default=list)),
                ('highlights', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
            },
        ),
    ]
