# Generated by Django 5.2.7 on 2025-10-26 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_course_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Placement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=150)),
                ('company_logo', models.ImageField(upload_to='placements/company_logos/')),
                ('student_image', models.ImageField(upload_to='placements/students/')),
                ('background_image', models.ImageField(upload_to='placements/backgrounds/')),
            ],
        ),
    ]
