# Generated by Django 5.2.7 on 2025-10-26 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_placement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placement',
            name='background_image',
            field=models.ImageField(upload_to='placements/'),
        ),
        migrations.AlterField(
            model_name='placement',
            name='company_logo',
            field=models.ImageField(upload_to='placements/'),
        ),
        migrations.AlterField(
            model_name='placement',
            name='student_image',
            field=models.ImageField(upload_to='placements/'),
        ),
    ]
