# Generated by Django 5.2.7 on 2025-10-26 06:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_placement_background_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='placement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='placement',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
