# Generated by Django 5.2.7 on 2025-10-26 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_galleryitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='top_choice',
            field=models.BooleanField(default=False),
        ),
    ]
